### ISSUE TITLE
Please change your download links

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [sumatrapdfreader/sumatra-website#2]
I found PRC people is hard to download your software now. PRC have blocked Amazon Web Service last year, so many service from there have been disturbed. Their ISP (de facto controlled by Communist authority) can also break the link by DNS poisoning. So please change your download links to other available service.

**Comment by kjk** [comment]
We don't have the resources to fight whatever restrictions various governments create.

Anyone can rehost the files on another server but I'm not in the position to figure out what is and isn't blocked by PRC.

**Comment by KrasnayaPloshchad** [comment]
GreatFire.org may can figure out what is and isn't blocked by CPC authority.
